#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#           noncompliant, but you have some other compliant shell such as ksh or
#           bash, then to run this script, type that shell name before the whole
#           command line, like:
#
#               ksh Gradle
#
#       (2) This script is suitable for both Unix and Linux.
#
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

GRADLE_USER_HOME="${GRADLE_USER_HOME:-${HOME}/.gradle}"

exec gradle "$@"
